package it.unipi.findyourdoc.dto.mongo;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Lightweight DTO for symptom analysis summaries.
 * Used for listing historical diagnostic reports in patient or doctor dashboards.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "DTO representing a summary of a symptom analysis report")
public class SymptomReportBriefDTO {

    /** * User-provided notes regarding the circumstances of the symptoms. */
    @Schema(description = "Additional context or notes provided by the user", example = "Symptoms felt after physical activity")
    private String context;

    /** * Collection of clinical signs reported by the patient. */
    @Schema(description = "List of symptoms reported by the patient", example = "['Cough', 'Shortness of breath']")
    private List<String> symptoms;

    /** * Results generated by the Neo4j-based inference engine. */
    @Schema(description = "List of possible diseases identified by the system", example = "['Asthma', 'Bronchitis']")
    private List<String> possibleDiagnosies;

    /** * Timestamp of when the diagnostic session was concluded. */
    @Schema(description = "The date and time when the report was generated", example = "2026-01-22T17:00:00")
    private LocalDateTime createdAt;
}